### PR TITLE
Fixed route-prefix import issue by using a dynamic `import()` statement to grab greensock.

### LINKED ISSUE #112: [BUG] Resolution of greensock script path is erroneous on non-standard route prefixes
**Describe the bug**
I host my server on a non-default route and for whatever reason, this breaks fetching of several mars script files.
The import path for this greensock script is absolute, and thus fails to resolve for any some-standard hosting configurations.

image

**To Reproduce**
1. Host foundry on a non-root url (in my case, www.fakewebsite.com/tartarus, on port 40000)
2. Install and enable MARS.
3. Observe that MARS fails to load
4. See errors in console

**Expected behavior**
The path should resolve regardless. My suggestion would be to respect the ROUTE_PREFIX and the dataPath config variable (though I am unsure where to find dataPath specifically, this shouldn't be relevant for the greenSock script).

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Firefox + Chrome
 - FVTT Version 0.8.9
 - Module version [e.g. 0.1.0]
 - Hosted on a Linode ubuntu instance, using NGINX for routing. 

**Additional context**
I get that my hosting setup is nonstandard, but I'm running 3 instances. I can provide any further info as needed, but the above should be plenty to get started on adjusting import paths to respect route prefix (or at least be relative).

### PR DESCRIPTION
**Pull request by whitespine**
Fixes #112 

Should work on all modern browsers, based on https://caniuse.com/?search=import(). That being said, I do not know how to test it on the Electron app, having never used it myself.

Pretty quick and dirty fix. Let me know if anything seems amiss.

### CODE REVIEW

**Comment by Moerill** [comment]
I'd prefer it to not use the async call, as that can result in some other issues downstream that i encountered previously. (either here or somewhere else)
The better approach would be to just move the import into the manifest (module.json) and let foundry do the path redirecting. 

I kind of that i did that change at some point, but i seem to've forgotten it here. (And don't really have the time to make and test that change atm.)

**Comment by whitespine** [comment]
Is there another module where you already did change it that I could attempt to replicate? Like MESS or something?

**Comment by whitespine** [comment]
Could've just looked myself- found an example. I'll change and check that it work tonight hopefully.

**Comment by whitespine** [comment]
Mimicked https://github.com/Moerill/fvtt-chat-notifications instead.

**Comment by whitespine** [comment]
Any thoughts or requests for changes on this?

**Comment by Moerill** [comment]
Oh sorry, i've been (and still am) very busy and forgot about this...
Does look fine! 
i'll merge it and try to remember to properly pack it to a new release in the next days.

**Pull request merged**
